## Numpy tutorials

- NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

## What is an array

- An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type


In [1]:
# lets import numpy as np

import numpy as np

In [4]:
array = np.array([1,2,3,4]) 

In [5]:
array

array([1, 2, 3, 4])

In [6]:
type(array)

numpy.ndarray

In [38]:
## Multi Nested Array

array2 = np.array([[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15]
         ]) 

In [9]:
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
type(array2)

numpy.ndarray

In [12]:
## check the shape of the array

array2.shape

(3, 5)

### Indexing

In [45]:
## Accessing the array elements

array

array([1, 2, 3, 4])

In [15]:
array[3]

4

In [22]:
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [17]:
array2[1:,1:3]

array([[ 7,  8],
       [12, 13]])

In [28]:
## Reshaping the multi dimension array
array2.reshape(1,15)
array2.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [29]:
array2[:, 2:]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [32]:
array2[1:2, :3]

array([[6, 7, 8]])

In [39]:
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [40]:
array2[2:, 1:] = 200

In [41]:
array2

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11, 200, 200, 200, 200]])

In [47]:
### Some conditions very useful in Exploratory Data Analysis 

val = 2

array[array < 5]

array([1, 2, 3, 4])

In [50]:
## Create arrays and reshape

arr = np.arange(0,10)

In [51]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])